apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Local images (built with minikube docker-env -> eval $(minikube docker-env))
images:
  - name: fullstack-backend:v1.0
    newName: fullstack-backend
    newTag: v1.0
  - name: fullstack-frontend:v1.0
    newName: fullstack-frontend
    newTag: v1.0
  - name: fullstack-frontend-v2:v1.0
    newName: fullstack-frontend-v2
    newTag: v1.0
