apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-devops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reggiegunawan88/fullstack-devops.git
    targetRevision: master
    path: k8s/overlays/ecr
  destination:
    server: https://kubernetes.default.svc
    namespace: fullstack-devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
