apiVersion: v1
kind: Service
metadata:
  name: fullstack-backend
  labels:
    app: fullstack-backend-service
spec:
  selector:
    deployment: fullstack-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
