apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend
  labels:
    app: fullstack-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-backend
  template:
    metadata:
      labels:
        deployment: fullstack-backend
    spec:
      containers:
        - name: fullstack-backend
          image: fullstack-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: API_ENDPOINT
              value: "http://localhost:3001"
            - name: PORT
              value: "3001"
            - name: DEPLOYED_ON
              value: "local"
