apiVersion: v1
kind: Service
metadata:
  name: fullstack-frontend
  labels:
    app: fullstack-frontend-service
spec:
  selector:
    app: fullstack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
