apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-frontend-v2
  labels:
    deployment: fullstack-frontend-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-frontend-v2
  template:
    metadata:
      labels:
        app: fullstack-frontend-v2
    spec:
      containers:
        - name: fullstack-frontend-v2
          image: fullstack-frontend-v2:v1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: "http://localhost:3001"
