apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fullstack-backend-deployment.yaml
  - fullstack-frontend-deployment.yaml
  - fullstack-frontend-v2-deployment.yaml
  - fullstack-backend-service.yaml
  - fullstack-frontend-service.yaml
  - fullstack-frontend-v2-service.yaml
  - ingress.yaml
